source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!

target 'MasonryNote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MasonryNote
  pod 'Masonry', '1.1.0'

end
