source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!

target 'SDWebImageNote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDWebImageNote
  pod 'SDWebImage', '5.11.1'

end
