source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!

target 'FMDBNote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FMDBNote
  pod 'FMDB', '2.7.5'

end
